# Generated by Django 3.0.4 on 2020-03-17 14:33

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='empty.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kingdom', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('description', ckeditor.fields.RichTextField()),
                ('dob', models.DateTimeField(default=datetime.date.today)),
                ('age', models.IntegerField(null=True)),
                ('DOB', models.DateField(default=datetime.date.today, max_length=8)),
                ('vaccinations', models.ManyToManyField(blank=True, to='myapp.vaccine')),
            ],
        ),
    ]
