# Generated by Django 3.0.4 on 2020-03-17 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='dob',
        ),
        migrations.AddField(
            model_name='animal',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='img',
            field=models.ImageField(blank=True, default='empty.png', upload_to='.animals_pics'),
        ),
    ]
