# Generated by Django 3.0.4 on 2020-03-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_animal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='slug',
        ),
    ]
