# Generated by Django 3.0.4 on 2020-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200318_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='img',
            field=models.ImageField(blank=True, default='empty.png', upload_to='.media'),
        ),
    ]
